<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RecyclingMethod;

class RecyclingMethodSeeder extends Seeder
{
    public function run(): void
    {
        $methods = [
            // Fort Portal
            [
                'name' => 'Plastic Melting and Recasting',
                'description' => 'Recycling plastics by melting and recasting into usable products.',
                'organisation_id' => 2,
            ],
            [
                'name' => 'Organic Composting',
                'description' => 'Decomposition of organic matter to produce compost.',
                'organisation_id' => 2,
            ],

            // Jinja
            [
                'name' => 'Metal Sorting and Smelting',
                'description' => 'Sorting and melting metal waste for reuse.',
                'organisation_id' => 3,
            ],
            [
                'name' => 'Paper Pulping',
                'description' => 'Recycling paper into pulp for creating new paper products.',
                'organisation_id' => 3,
            ],
        ];

        foreach ($methods as $method) {
            RecyclingMethod::create($method); // uuid is auto-generated by model boot
        }
    }
}
